name: Build

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }} - Python ${{ matrix.python-version }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13]
        arch: [x86_64, arm64]
        python-version: ["38", "39", "310", "311"]
        exclude:
          - os: macos-13
            arch: arm64
            python-version: 3.8
          - os: ubuntu-latest
            arch: arm64

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.18.1
        env:
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_BUILD: cp${{ matrix.python-version }}-*
          CIBW_BUILD_VERBOSITY: 3
          CIBW_SKIP: "*musllinux*"
          CIBW_ARCHS_LINUX: ${{ matrix.arch }}
          CIBW_ENVIRONMENT_LINUX: >
            CFLAGS="-I/usr/include/GL" LDFLAGS="-L/usr/lib64 -lGL"
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: >
            auditwheel repair -w {dest_dir} {wheel} ||
            cp {wheel} {dest_dir}/

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.python-version }}-${{ matrix.os }}-${{ matrix.arch }}
          path: ./wheelhouse/*.whl

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.PYSTK_SECRET }}
          file: ./wheelhouse/*.whl
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

# for more info see https://github.com/pypa/cibuildwheel/blob/main/examples/github-deploy.yml
