name: Build

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build wheel for cp${{ matrix.python }}-${{ matrix.platform_id }}-${{ matrix.manylinux_image }}
    runs-on: ${{ matrix.os }}

    # strategy:
    #   matrix:
    #     os: [ubuntu-20.04, macOS-10.15]

    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python: 38
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014
          - os: ubuntu-latest
            python: 39
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014
          - os: ubuntu-latest
            python: 310
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014
          - os: ubuntu-latest
            python: 311
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014
          # doesnt work yet
          # - os: ubuntu-latest
          #   python: 312
          #   platform_id: manylinux_x86_64
          #   manylinux_image: manylinux2014

          # MacOS x86_64
          - os: macos-12
            python: 38
            platform_id: macosx_x86_64
          - os: macos-12
            python: 39
            platform_id: macosx_x86_64
          - os: macos-12
            python: 310
            platform_id: macosx_x86_64
          - os: macos-12
            python: 311
            platform_id: macosx_x86_64

          # MacOS arm64
          - os: macos-14
            python: 38
            platform_id: macosx_arm64
          - os: macos-14
            python: 39
            platform_id: macosx_arm64
          - os: macos-14
            python: 310
            platform_id: macosx_arm64
          - os: macos-14
            python: 311
            platform_id: macosx_arm64

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.18.1

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.PYSTK_SECRET }}
          file: ./wheelhouse/*.whl
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

# for more info see https://github.com/pypa/cibuildwheel/blob/main/examples/github-deploy.yml
